# Generated by Django 3.0.2 on 2021-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
