# Generated by Django 3.1.5 on 2021-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_goal_pause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='pause',
        ),
        migrations.AddField(
            model_name='goal',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
