# Generated by Django 3.1.5 on 2021-02-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('goal', '0003_auto_20210223_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='contribLog',
            fields=[
                ('conId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user_details')),
            ],
        ),
    ]
