# Generated by Django 3.1.5 on 2021-02-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_contriblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contriblog',
            name='goal',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='goal.goal'),
            preserve_default=False,
        ),
    ]
