# Generated by Django 3.1.5 on 2021-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=12)),
                ('bdate', models.DateField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
