# Generated by Django 3.1.5 on 2021-01-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='income_details',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('regular', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user_details')),
            ],
        ),
    ]
