# Generated by Django 3.1.5 on 2021-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_details',
            name='incomeID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income_details',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
